# cmake/cmake_tools_version.cmake

# V 0.0.0
set(CMAKE_TOOLS_VERSION_MAJOR 0)
set(CMAKE_TOOLS_VERSION_MINOR 1)
set(CMAKE_TOOLS_VERSION_PATCH 0)

set(CMAKE_TOOLS_VERSION
  "${CMAKE_TOOLS_VERSION_MAJOR}.${CMAKE_TOOLS_VERSION_MINOR}.${CMAKE_TOOLS_VERSION_PATCH}"
)
